Update Dutch translations
sandboxie-plus/Sandboxie pull request #1035
Opened 2021-07-24 17:59 UTC by RockyTDR

Update Dutch translations for Sandboxie Classic and Sandboxie-Plus

2021-07-24 20:07 UTC, isaak654 requested changes

2021-07-24 20:07 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_nl.ts
> +        <translation>Wilt u %4 (%5) toestaan om een %1 groot bestand te kopiëren naar sandbox %2?&lt;byte value=&quot;xd&quot;/&gt;
Byte value here has a strange format, it looks different than the `<byte value="xd"/>` that you can find two lines above.

Same goes for the following lines below: 658, 665, 688, 1054-1055 and 1135-1136

2021-07-24 20:11 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_nl.ts
> +        <translation>Wilt u %4 (%5) toestaan om een %1 groot bestand te kopiëren naar sandbox %2?&lt;byte value=&quot;xd&quot;/&gt;
I think I understood the issue... you don't need any byte value inside the translation tags. The code was only required for source tags.

Please remove those references that you're trying to add.

2021-07-24 21:38 UTC, RockyTDR commented on SandboxiePlus/SandMan/sandman_nl.ts
> +        <translation>Wilt u %4 (%5) toestaan om een %1 groot bestand te kopiëren naar sandbox %2?&lt;byte value=&quot;xd&quot;/&gt;
Done! `Sandman_nl.ts` now only has a colon changed. The other translation edits were in the Sandboxie Classic. 

Note that other translators will also see (and translate) the byte codes because they are part of the source string.

2021-07-24 22:25 UTC, isaak654 commented
> 
> 
> Done! `Sandman_nl.ts` now only has a colon changed. The other translation edits were in the Sandboxie Classic.
> 
> Note that other translators will also see (and translate) the byte codes because they are part of the source string.

@RockyTDR

Unfortunately it's the only workaround we know at this moment to force the translation of single english strings with multiple lines in other languages. For example, this is what appears without the byte codes: ![recovery_window](https://user-images.githubusercontent.com/12372772/126882227-32886852-922b-4a6b-acee-02430327f90b.png)

Any other alternative would be welcome.

2021-07-25 09:29 UTC, RockyTDR commented
> 
> 
> > Done! `Sandman_nl.ts` now only has a colon changed. The other translation edits were in the Sandboxie Classic.
> > Note that other translators will also see (and translate) the byte codes because they are part of the source string.
> 
> @RockyTDR
> 
> Unfortunately it's the only workaround we know at this moment to force the translation of single english strings with new lines in other languages. For example, this is what appears without the byte codes: ![recovery_window](https://user-images.githubusercontent.com/12372772/126882227-32886852-922b-4a6b-acee-02430327f90b.png)
> 
> Any other alternative would be welcome.

Ok. Thanks for the info! Can this PR be approved?

2021-07-25 20:59 UTC, isaak654 approved these changes

2021-07-26 06:17 UTC, merged