edits to English labeltext
sandboxie-plus/Sandboxie pull request #114
Opened 2020-08-16 06:09 UTC by antix-skidoo

2020-10-01 17:14 UTC, robdplatt approved these changes

2020-11-04 23:00 UTC, krystian3w approved these changes

2020-11-26 02:16 UTC, dnlck84 requested changes
Please also fix the misspelled word _enchancing,_ changing it to _enhancing_

2020-11-26 02:34 UTC, dnlck84 reviewed
The two strings work better as one sentence. Without connecting them as I've suggested or making the second into a sentence of its own, the text is problematic.

2020-11-26 02:34 UTC, dnlck84 commented on SandboxiePlus/SandMan/SandMan.cpp
> +			"<p>Sandboxie-Plus is a powerful sandboxing and application virtualization tool. Based on the well-known <a href=\"https://www.sandboxie.com\">Sandboxie</a>.</p>"
```suggestion
			"<p>Sandboxie-Plus is a powerful sandboxing and application virtualization tool based on the well-known <a href=\"https://www.sandboxie.com\">Sandboxie</a>.</p>"

```

2020-11-26 10:23 UTC, krystian3w approved these changes

2020-11-30 13:23 UTC, closed without merging