Update Languages.iss, Text-PortugueseBr-1046.txt and sandman_pt.ts
sandboxie-plus/Sandboxie pull request #1158
Opened 2021-09-01 17:42 UTC by JNylson

2021-09-01 23:47 UTC, isaak654 requested changes

2021-09-01 23:47 UTC, isaak654 commented on Sandboxie/msgs/Text-PortugueseBr-1046.txt
> +
Remove line 497

2021-09-02 22:57 UTC, JNylson commented on Sandboxie/msgs/Text-PortugueseBr-1046.txt
> +
Line 497 removed

2021-09-02 22:58 UTC, isaak654 approved these changes

2021-09-03 01:24 UTC, merged