Update sandman_nl.ts
sandboxie-plus/Sandboxie pull request #1179
Opened 2021-09-10 15:21 UTC by RockyTDR

Update Dutch translations via Transifex.

2021-09-10 18:30 UTC, isaak654 requested changes

2021-09-10 18:30 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_nl.ts
> -&apos;Direct&apos; File and Key access only applies to program binaries located outside the sandbox.
Unless they're causing issues in your tests, I think you may consider to restore these `&apos;` because they're in the english file too:
https://github.com/sandboxie-plus/Sandboxie/blob/99c36ef8fe8a8cb305d8d2c605dd258a7a290315/SandboxiePlus/SandMan/sandman_en.ts#L2956

2021-09-11 10:45 UTC, isaak654 requested changes

2021-09-11 10:45 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_nl.ts
> +            File and Key access only applies to program binaries located outside the sandbox.
I would recommend to merge 2971 and 2972 in one line

2021-09-11 10:54 UTC, RockyTDR commented on SandboxiePlus/SandMan/sandman_nl.ts
> +            File and Key access only applies to program binaries located outside the sandbox.
Done!

2021-09-11 14:38 UTC, isaak654 approved these changes

2021-09-11 14:38 UTC, merged