Update Portuguese translation
sandboxie-plus/Sandboxie pull request #1197
Opened 2021-09-15 02:18 UTC by JNylson

2021-09-15 12:55 UTC, isaak654 requested changes

2021-09-15 12:55 UTC, isaak654 commented on Installer/Languages.iss
> +portuguese.UninstallTaskLabel5=Remover arquivos de configuração e &caixas de areia%nSelecione essa opção para remover todos os arquivos de configuração e caixas de areia, incluindo a pasta Sandbox lo
If you decide to set accelerator keys (identified with ampersands), each button should have a different character.
UninstallTaskLabel4 and UninstallTaskLabel5 will have the same `c` character set as accelerator key and it's not ideal.
Source: https://github.com/sandboxie-plus/Sandboxie/pull/1058#issuecomment-915274213

2021-09-15 20:34 UTC, JNylson commented on Installer/Languages.iss
> +portuguese.UninstallTaskLabel5=Remover arquivos de configuração e &caixas de areia%nSelecione essa opção para remover todos os arquivos de configuração e caixas de areia, incluindo a pasta Sandbox lo
Fixed

2021-09-16 16:13 UTC, isaak654 approved these changes

2021-09-18 11:53 UTC, merged