Update Text-SimpChinese-2052.txt
sandboxie-plus/Sandboxie pull request #1414
Opened 2021-12-05 14:36 UTC by nkh0472

Thank you for your contribution to the Sandboxie repository.

In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request". You can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

2021-12-05 14:54 UTC, isaak654 requested changes

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
Empty line to remove.

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +.
Add a new line after the dot.

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +.
Add a new line after the dot.

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +.
Add a new line after the dot.

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +.
Add a new line after the dot.

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +.
Add a new line after the dot.

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +.
Add a new line after the dot.

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 14:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +# .
Add a new line after `# .`

2021-12-05 16:05 UTC, isaak654 requested changes
I would comment out 7923, 7941, 7945, 7946. 
I don't see any reference for these in the source code, except in the same .txt localization files, for example see https://github.com/sandboxie-plus/Sandboxie/search?q=7923

In case you're looking to comment out more lines, you could take a look to my changes [here](https://github.com/sandboxie-plus/Sandboxie/blob/364c43f29bb4f4a4b667d393a5e396b93c6c62ef/Sandboxie/msgs/Text-Italian-1040.txt)

2021-12-06 01:29 UTC, nkh0472 commented
> In case you're looking to comment out more lines, you could take a look to my changes [here](https://github.com/sandboxie-plus/Sandboxie/blob/364c43f29bb4f4a4b667d393a5e396b93c6c62ef/Sandboxie/msgs/Text-Italian-1040.txt)

Since I found some differences between the English and Italian translation file, and the project are written in English, I'll decide to keep my translation as same as the [English msg file](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/Sbie-English-1033.txt).

If you want to comment out more deprecated strings, it may be better to merge commented lines in both languages, then comment out (or delete?) all those lines in all language files at once.

<details>
<summary>diff between En and It</summary>

```
diff -r X:\en_sta.txt X:\it_sta.txt
9c9
< 1109;evt;err;01
---
> # 1109;evt;err;01
24c24
< 1202;pop;err;01
---
> # 1202;pop;err;01
35c35
< 1222;pop;err;02
---
> 1222;pop;err;01
43c43
< 1303;pop;inf;01
---
> # 1303;pop;inf;01
49c49
< 1310;pop;inf;01
---
> # 1310;pop;inf;01
51,52c51,52
< 1312;pop;inf;01
< 1313;pop;inf;01
---
> # 1312;pop;inf;01
> # 1313;pop;inf;01
198c198
< 3231;txt;01
---
> # 3231;txt;01
200,207c200,207
< 3233;txt;01
< 3234;txt;01
< 3235;txt;01
< 3236;txt;01
< 3237;txt;01
< 3238;txt;01
< 3239;txt;01
< 3240;txt;01
---
> # 3233;txt;01
> # 3234;txt;01
> # 3235;txt;01
> # 3236;txt;01
> # 3237;txt;01
> # 3238;txt;01
> # 3239;txt;01
> # 3240;txt;01
276c276
< 3455;txt;01
---
> # 3455;txt;01
279c279
< 3458;txt;01
---
> # 3458;txt;01
466c466
< 3771;txt;01
---
> # 3771;txt;01
491d490
< # 3821;txt;01
495d493
< # 3831;txt;01
502d499
< # 3841;txt;01
510d506
< # 3851;txt;01
521d517
< # 3861;txt;01
528d523
< # 3871;txt;01
531d525
< # 3961;txt;01
536d529
< # 3881;txt;01
540d532
< # 3891;txt;01
551d542
< # 3911;txt;01
562d552
< # 3921;txt;01
568,580c558,567
< # 3931;txt;01
< # 3932;txt;01
< # 3933;txt;01
< # 3934;txt;01
< # 3935;txt;01
< # 3936;txt;01
< # 3937;txt;01
< # 3938;txt;01
< # 3951;txt;01
< # 3952;txt;01
< # 3953;txt;01
< # 3954;txt;01
< # 3941;txt;01
---
> 3932;txt;01
> 3933;txt;01
> 3934;txt;01
> 3935;txt;01
> 3936;txt;01
> 3937;txt;01
> 3938;txt;01
> 3952;txt;01
> 3953;txt;01
> 3954;txt;01
585,586c572,573
< # 3946;txt;01
< # 3947;txt;01
---
> 3946;txt;01
> 3947;txt;01
588,591d574
< 3950;txt;01
< 3951;txt;01
< 3952;txt;01
< 3953;txt;01
652d634
< # 4208;txt;01
713d694
< # 4301;txt;01
788,828c769,809
< 7901;txt;01
< 7902;txt;01
< 7903;txt;01
< 7921;txt;01
< 7922;txt;01
< 7923;txt;01
< 7924;txt;01
< 7925;txt;01
< 7926;txt;01
< 7927;txt;01
< 7931;txt;01
< 7932;txt;01
< 7933;txt;01
< 7934;txt;01
< 7935;txt;01
< 7936;txt;01
< 7937;txt;01
< 7941;txt;01
< 7942;txt;01
< 7943;txt;01
< 7944;txt;01
< 7945;txt;01
< 7946;txt;01
< 7951;txt;01
< 7952;txt;01
< 7961;txt;01
< 7962;txt;01
< 7971;txt;01
< 7972;txt;01
< 7973;txt;01
< 7974;txt;01
< 7975;txt;01
< 7976;txt;01
< 7977;txt;01
< 7978;txt;01
< 7982;txt;01
< 7983;txt;01
< 7984;txt;01
< 7985;txt;01
< 7986;txt;01
< 7987;txt;01
---
> # 7901;txt;01
> # 7902;txt;01
> # 7903;txt;01
> # 7921;txt;01
> # 7922;txt;01
> # 7923;txt;01
> # 7924;txt;01
> # 7925;txt;01
> # 7926;txt;01
> # 7927;txt;01
> # 7931;txt;01
> # 7932;txt;01
> # 7933;txt;01
> # 7934;txt;01
> # 7935;txt;01
> # 7936;txt;01
> # 7937;txt;01
> # 7941;txt;01
> # 7942;txt;01
> # 7943;txt;01
> # 7944;txt;01
> # 7945;txt;01
> # 7946;txt;01
> # 7951;txt;01
> # 7952;txt;01
> # 7961;txt;01
> # 7962;txt;01
> # 7971;txt;01
> # 7972;txt;01
> # 7973;txt;01
> # 7974;txt;01
> # 7975;txt;01
> # 7976;txt;01
> # 7977;txt;01
> # 7978;txt;01
> # 7982;txt;01
> # 7983;txt;01
> # 7984;txt;01
> # 7985;txt;01
> # 7986;txt;01
> # 7987;txt;01
```
</details>

2021-12-06 04:34 UTC, isaak654 approved these changes

2021-12-06 04:52 UTC, merged

2022-07-14 12:07 UTC, isaak654 commented
> If you want to comment out more deprecated strings, it may be better to merge commented lines in both languages

So far, this has already been completed for English, Italian, Russian and German languages.

> then comment out (or delete?) all those lines in all language files at once.

It should preferably be done by the translator itself, so for Simplified Chinese you may want to look at [Report-SimpChinese.txt](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/report/Report-SimpChinese.txt)