Updated Russian translation
sandboxie-plus/Sandboxie pull request #1555
Opened 2022-01-18 12:07 UTC by lufog

2022-01-18 12:13 UTC, isaak654 requested changes

2022-01-18 12:13 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_ru.ts
> +        <translation>Срок действия сертификата сторонника истек %1, получите обновленный сертификат</translation>
The extra space before %1 is not needed, see https://github.com/sandboxie-plus/Sandboxie/commit/06157fd83376a190757803d88221e319e6b99dd7

2022-01-18 12:19 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_ru.ts
> +        <translation>Срок действия сертификата сторонника истек %1, получите обновленный сертификат</translation>
I would also suggest to delete line 1350, since it's not used anymore.

2022-01-19 10:49 UTC, lufog commented on SandboxiePlus/SandMan/sandman_ru.ts
> +        <translation>Срок действия сертификата сторонника истек %1, получите обновленный сертификат</translation>
Done

2022-01-19 10:49 UTC, isaak654 approved these changes

2022-01-19 10:51 UTC, merged