Adds Brave, Waterfox and Opera to BlockSoftwareUpdaters
sandboxie-plus/Sandboxie pull request #1630
Opened 2022-02-14 18:21 UTC by Dyras

Hello. This adds 3 new browsers to BlockSoftwareUpdaters. Planning on throwing in Edge, Vivaldi and Pale Moon tomorrow.

2022-02-16 15:17 UTC, isaak654 requested changes

2022-02-16 15:17 UTC, isaak654 commented on Sandboxie/install/Templates.ini
> +SoftwareUpdater=opera.exe,*\Opera\opera_autoupdate.exe
It would be probably better to add below:
`SoftwareUpdater=launcher.exe,*\Opera\opera_autoupdate.exe`

Source: 
https://www.reddit.com/r/operabrowser/comments/goiniy/update_is_automatically_launched_by_exe_and_there

2022-02-16 20:11 UTC, Dyras commented on Sandboxie/install/Templates.ini
> +SoftwareUpdater=opera.exe,*\Opera\opera_autoupdate.exe
Planning on adding all the browsers first, then I'll think about the sorting. Will probably be done early next week.

2022-03-08 10:36 UTC, Dyras commented
Every mainstream web browser is added now. I'm thinking I will do the minor ones next week or something. I've been busy with school and work lately

2022-03-08 10:48 UTC, isaak654 commented
Before merging, do you have any suggestion about [this](https://github.com/sandboxie-plus/Sandboxie/issues/1602#issuecomment-1059333850)?

2022-03-08 10:52 UTC, Dyras commented
I think we could disable it and see how that will work out with people. If it causes confusion we can always consider adding it back in a changed form

(A helicopter has been hovering outside my apartment for the past 4 hours so if that makes no sense, that's why)

2022-03-14 21:08 UTC, isaak654 approved these changes
It looks good now, next time is the turn of minor browsers.

2022-03-14 21:31 UTC, merged