Change license.txt
sandboxie-plus/Sandboxie pull request #1726
Opened 2022-03-25 14:58 UTC by totsukasaika

Sandboxie is provided under the GPLv3, modifications must be released under the same license when distributing the licensed material.

please see: https://choosealicense.com/licenses/gpl-3.0/

2022-03-25 17:16 UTC, isaak654 commented
The GPLv3 license is already mentioned in these files: 
* [LICENSE](https://github.com/sandboxie-plus/Sandboxie/blob/master/LICENSE) Sandboxie
* [install/LICENSE.TXT](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/install/LICENSE.TXT) - Sandboxie Classic Installer

While [Installer/license.txt](https://github.com/sandboxie-plus/Sandboxie/pull/1726/files#diff-511832906cfe39a6d264bdcc35404f894ed643dc37a3fbc43f18f132979728cd) seems more related to the Sandman installer that is not under the GPLv3: https://github.com/sandboxie-plus/Sandboxie/pull/1383#issuecomment-974326425

> Only Sandboxie is GPLv3, Sandboxie Plus's SandMan.exe as it does not load any code from the old project and only uses regular IPC communication mechanisms hence it has an own license, once that does not allow for commercial usage of SandMan.exe without permission. The components are distributed as a aggregation and if you want 100% GPL you can always stick with using SbieCtrl.exe

Suggestion: You may want to edit [Installer/README.md](https://github.com/sandboxie-plus/Sandboxie/pull/1726/files#diff-6ba86e3f6d7c8cbf2f7a16fc6978e3a2a73e3c6ec7648394e1da374ec8e47a05) in order to write how to create Sandboxie-Plus installers, as it was done for Sbie Classic: [install/ReadMe.txt](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/install/ReadMe.txt).

2022-03-25 17:22 UTC, isaak654 requested changes
The GPLv3 license is already mentioned in these files: 
* [LICENSE](https://github.com/sandboxie-plus/Sandboxie/blob/master/LICENSE) Sandboxie
* [install/LICENSE.TXT](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/install/LICENSE.TXT) - Sandboxie Classic Installer

While [Installer/license.txt](https://github.com/sandboxie-plus/Sandboxie/blob/master/Installer/license.txt) seems more related to the Sandman installer that is not under the GPLv3: https://github.com/sandboxie-plus/Sandboxie/pull/1383#issuecomment-974326425

> Only Sandboxie is GPLv3, Sandboxie Plus's SandMan.exe as it does not load any code from the old project and only uses regular IPC communication mechanisms hence it has an own license, once that does not allow for commercial usage of SandMan.exe without permission. The components are distributed as a aggregation and if you want 100% GPL you can always stick with using SbieCtrl.exe

Suggestion: You may want to edit [Installer/README.md](https://github.com/sandboxie-plus/Sandboxie/pull/1726/files#diff-6ba86e3f6d7c8cbf2f7a16fc6978e3a2a73e3c6ec7648394e1da374ec8e47a05) in order to write how to create Sandboxie-Plus installers, as it was done for Sbie Classic: [install/ReadMe.txt](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/install/ReadMe.txt).

2022-03-25 17:54 UTC, isaak654 requested changes

2022-03-25 17:54 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_zh_TW.ts
> +        <translation>New Box</translation>
This needs to be ported on a dedicated PR.

Also, I would suggest to inform the most active translator @Hulen, since it looks like the mentioned string has been changed a number of times already.

2022-03-25 18:01 UTC, DavidXanatos commented
@totsukasaika the license of the new binaries which were written from scratch and that run in own processes will not be changed, aggregation of GPL tools with other non GPL tools is a common industry praxis.

2022-03-26 06:22 UTC, Hulen commented on SandboxiePlus/SandMan/sandman_zh_TW.ts
> +        <translation>New Box</translation>
Ok, I'll pay attention to this later. Thank you.

2022-03-26 13:25 UTC, closed without merging