Update sandman_es.ts
sandboxie-plus/Sandboxie pull request #1740
Opened 2022-03-30 00:58 UTC by sebadamus

Some extra text corrections!

2022-03-30 01:12 UTC, isaak654 requested changes

2022-03-30 01:12 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_es.ts
> +        <source>Prompt user for large file migration.</source>
```suggestion
        <source>Prompt user for large file migration</source>
```
See the following remark from the [Localization notes](https://github.com/sandboxie-plus/Sandboxie/discussions/1123):

> ⚠️ You shouldn't ever edit the text in the source tags of the .ts file if you don't apply the same edit on the respective source code file. For example, see the following commit: [3b86441](https://github.com/sandboxie-plus/Sandboxie/commit/3b864411275ac0fa6e60ea1544feb176b470c049).

2022-03-30 01:12 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_es.ts
> +        <translation>Preguntar al usuario si desea migrar archivos grandes.</translation>
```suggestion
        <translation>Preguntar al usuario si desea migrar archivos grandes</translation>
```

2022-03-30 01:12 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_es.ts
> +        <source>Note: MSI Installer Exemptions should not be required, but if you encounter issues installing a MSI package which you trust, this option may help the installation complete successfull
```suggestion
        <source>Note: Msi Installer Exemptions should not be required, but if you encounter issues installing a msi package which you trust, this option may help the installation complete successfully. You can also try disabling drop admin rights.</source>
```

See the following remark from the [Localization notes](https://github.com/sandboxie-plus/Sandboxie/discussions/1123):

> ⚠️ You shouldn't ever edit the text in the source tags of the .ts file if you don't apply the same edit on the respective source code file. For example, see the following commit: [3b86441](https://github.com/sandboxie-plus/Sandboxie/commit/3b864411275ac0fa6e60ea1544feb176b470c049).

2022-03-30 15:50 UTC, sebadamus commented on SandboxiePlus/SandMan/sandman_es.ts
> +        <translation>Preguntar al usuario si desea migrar archivos grandes.</translation>
OK

2022-03-30 15:51 UTC, sebadamus commented on SandboxiePlus/SandMan/sandman_es.ts
> +        <source>Note: MSI Installer Exemptions should not be required, but if you encounter issues installing a MSI package which you trust, this option may help the installation complete successfull
OK got it!

2022-03-30 16:05 UTC, sebadamus reviewed
There I fixed my working file not to post this changes in future commits.  Hope its ok now.

2022-04-02 00:33 UTC, isaak654 commented
The file is the same as before, you will need to overwrite it on [this branch](https://github.com/sebadamus/Sandboxie/tree/patch-4/SandboxiePlus/SandMan) in order to see the updated one here.

2022-04-02 23:28 UTC, sebadamus commented
> The file is the same as before, you will need to overwrite it on [this branch](https://github.com/sebadamus/Sandboxie/tree/patch-4/SandboxiePlus/SandMan) in order to see the updated one here.

There, have just done it! tell me if it is okay now, sorry for the mess.

https://github.com/sebadamus/Sandboxie/blob/patch-4/SandboxiePlus/SandMan/sandman_es.ts

2022-04-02 23:34 UTC, isaak654 approved these changes

2022-04-02 23:35 UTC, merged