fix:office ui
sandboxie-plus/Sandboxie pull request #1874
Opened 2022-05-20 07:35 UTC by weihongx9315

This commit fix bug of:us office 2016+ version (include 2019),you can see WINWORD.exe process is started,but you can't see the UI of WINWORD.exe.
The reason is when a process is started, but not the main thread load user32.dll,then other threads can't switch to the desktop,so hook ClientStartUp,to make sure every thread can switch to desktop.

2022-05-21 17:36 UTC, isaak654 requested changes

2022-05-21 17:36 UTC, isaak654 commented on Sandboxie/core/dll/gui.c
> +		// 避免重入
```suggestion
		// avoid re-entry
```

2022-05-21 19:15 UTC, DavidXanatos commented
I'm having issues running office in a normal box at all, but this fix is clearly for a normal box.
Do you install office with the click to run or the setup method?

2022-05-22 12:03 UTC, DavidXanatos commented
I have resolved my office issues mostly, nut cant reproduce the issue this fix fixes, for me even without it word starts up just fine now.
The fix looks safe enough and well made so we can pull it just in case it should not break anything, but i would prefer to first reproduce the issue. Currently running office 2021.

2022-05-22 14:25 UTC, DavidXanatos commented
I have investigated the issue a bit more and I wonder how the problem can happen in the first place, see https://github.com/sandboxie-plus/Sandboxie/blob/d93d4894aa503e1e3e83966524283116f7570fdf/Sandboxie/core/dll/dllmain.c#L148
the SbieDll.dll is calling Gui_ConnectToWindowStationAndDesktop already for each thread that is created.
Can you provide a call stack for ClientThreadSetup where the desktop initialization was missed?

Also the check for re-entry should be after the ConnectThread label IMHO

2022-05-25 03:39 UTC, weihongx9315 commented
I use office 2019 with the setup method,in this case, the gui can't show. Gui_ConnectToWindowStationAndDesktop(NULL);  can't work, you can see if (!User32) return FALSE.

2022-10-08 01:36 UTC, closed without merging