ocupied -> occupied
sandboxie-plus/Sandboxie pull request #2034
Opened 2022-07-16 19:10 UTC by Dyras

Hello! This fixes a minor spelling error under the Sandboxie-Plus settings.

2022-07-16 19:38 UTC, isaak654 commented
I think occupied is acceptable.

Next one: https://github.com/sandboxie-plus/Sandboxie/blob/58348273489a0c60aaf6a5c9404e613034d1b265/SandboxiePlus/SandMan/Forms/SettingsWindow.ui#L412

I think it should be translated as `* depending on the selected view mode`

If you fix this too, I'll make sure to update the pull request title.

2022-07-16 19:49 UTC, isaak654 requested changes

2022-07-16 19:49 UTC, isaak654 commented on SandboxiePlus/SandMan/Forms/SettingsWindow.ui
> +              <string>* indetermined means depending on the selected view mode</string>
```suggestion
              <string>* depending on the selected view mode</string>
```
Imho specifying also `indetermined means` can be confusing

2022-07-16 19:50 UTC, isaak654 requested changes

2022-07-16 19:50 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_en.ts
> +        <source>* indetermined means depending on the selected view mode</source>
https://github.com/sandboxie-plus/Sandboxie/pull/2034/files#r922714887

2022-07-16 19:56 UTC, Dyras commented on SandboxiePlus/SandMan/Forms/SettingsWindow.ui
> +              <string>* indetermined means depending on the selected view mode</string>
"indetermined depending on the selected view mode" Sounds better. Should I change it to that?

2022-07-16 20:10 UTC, isaak654 commented on SandboxiePlus/SandMan/Forms/SettingsWindow.ui
> +              <string>* indetermined means depending on the selected view mode</string>
Mmmm, not quite. 🤔

2022-07-16 20:11 UTC, Dyras commented on SandboxiePlus/SandMan/Forms/SettingsWindow.ui
> +              <string>* indetermined means depending on the selected view mode</string>
Where is this in the program anyway?

2022-07-16 20:31 UTC, isaak654 commented on SandboxiePlus/SandMan/Forms/SettingsWindow.ui
> +              <string>* indetermined means depending on the selected view mode</string>
The second one looks fine.

2022-07-16 21:06 UTC, DavidXanatos commented
<source>* indetermined means depending on the selected view mode</source>
        <source>* results may vary depending on the view mode</source>

is not quite right, this text must somehow indicate that the view mode only maters when the checkbox is in the intermediate/undetermined/half checked state

2022-07-16 21:10 UTC, Dyras commented
Then I'd suggest we change the string to include something that easier for the end user to understand. Something like:
* a gray box means the results will depend on the view mode

2022-07-16 21:21 UTC, DavidXanatos commented
well gray or something else depends on the ui style
best may be

"partially checked"

2022-07-16 23:01 UTC, isaak654 commented
Alternatively:

*  `* partially checked options depend on the view mode`
* `* a partially checked box always affects the view mode`
* `* a partially checked box can affect the view mode`
* `* a partially checked box will affect the view mode`
* `* partially checked options will affect the view mode`

2022-07-17 12:27 UTC, Dyras commented
I think this one sounds the best
`* a partially checked box can affect the view mode`
The only question is if it should be "can" or "will". @DavidXanatos will partially checked boxes always affect the view mode, or only in some scenarios?

2022-07-18 08:12 UTC, isaak654 commented
@Dyras 
<img alt="David_answer" src="https://user-images.githubusercontent.com/12372772/179468041-51b1f39b-3db9-4091-a320-e673afc5d88b.png" height="70px">
which means: 
`* a partially checked box will be affected by the view mode`

2022-07-18 21:14 UTC, Dyras commented
In my opinion
` * a partially checked checkbox will be affected by the view mode`
still sounds pretty confusing. It sounds to me as if _the checkbox_ will be affected by the view mode, not that the checkbox will have a different effect depending on the checkbox. 

Or maybe I'm just tired?

2022-07-18 21:53 UTC, DavidXanatos commented
Yea its not perfect I agree how about
* partially checked checkbox will leave the behavior to be determined by the view mode.

2022-07-19 07:28 UTC, Dyras commented
Sounds good to me!

2022-07-19 07:45 UTC, DavidXanatos commented
then please add it to the pull request and it can be merged

2022-07-19 20:45 UTC, isaak654 commented
I would get rid of the changes made in sandman_en.ts, I already set a scheduled workflow that runs when needed: https://github.com/sandboxie-plus/Sandboxie/commit/1de13ea51e4faecbb0675e75c8eb901103927e57

2022-07-19 20:46 UTC, isaak654 commented
I would get rid of the changes made in sandman_en.ts, now there is a scheduled workflow that runs when needed: https://github.com/sandboxie-plus/Sandboxie/commit/1de13ea51e4faecbb0675e75c8eb901103927e57

2022-07-20 08:42 UTC, isaak654 approved these changes

2022-07-20 08:43 UTC, merged