Update Text-Korean-1042.txt
sandboxie-plus/Sandboxie pull request #2153
Opened 2022-08-18 16:29 UTC by VenusGirl

2022-08-18 17:13 UTC, isaak654 requested changes

2022-08-18 17:13 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
> +Footer
```suggestion

```

2022-08-18 17:44 UTC, isaak654 requested changes
First round of suggested fixes.

2022-08-18 17:44 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
>  1222;pop;err;01
```suggestion
1222;pop;err;02
```

2022-08-18 17:44 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
>  1307;pop;inf;01
```suggestion
1307;pop;inf;02
```

2022-08-18 17:44 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
>  1308;pop;inf;01
```suggestion
1308;pop;inf;02
```

2022-08-18 17:44 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
>  3453;txt;01
```suggestion
3453;txt;02
```

2022-08-18 17:44 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
>  3688;txt;01
```suggestion
3688;txt;02
```

2022-08-18 17:44 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
>  3806;txt;01
```suggestion
3806;txt;02
```

2022-08-18 17:44 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
>  8014;ins;01
```suggestion
8014;ins;02
```

2022-08-18 17:52 UTC, isaak654 commented
#2150

2022-08-18 18:57 UTC, isaak654 requested changes
Second round of suggested fixes.

2022-08-18 18:57 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
>  9252;evt;err;01
```suggestion
# 9252;evt;err;01
```

2022-08-18 18:57 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
> +..
```suggestion
.
```

2022-08-18 19:16 UTC, isaak654 requested changes
Third round

2022-08-18 19:16 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
> +9253;evt;err;01
```suggestion
# 9253;evt;err;01
```

2022-08-18 20:08 UTC, isaak654 requested changes
I suspect there could be more duplicates, I recommend you to review the translation one last time.

2022-08-18 20:08 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
> +SBIE1313 SBIE1313 프로세스 '%2'에 의해 직접 디스크 접근이 차단되었습니다
```suggestion
SBIE1313 프로세스 '%2'에 의해 직접 디스크 접근이 차단되었습니다
```

2022-08-18 20:20 UTC, isaak654 requested changes

2022-08-18 20:20 UTC, isaak654 commented on Sandboxie/msgs/Text-Korean-1042.txt
> +SBIE9234서비스 시작 오류 %2
Missing space:
```suggestion
SBIE9234 서비스 시작 오류 %2
```

2022-08-19 08:23 UTC, isaak654 commented
Did you perform a final check?

2022-08-19 08:43 UTC, isaak654 commented
> Did you perform a final check?

@VenusGirl I am waiting for written confirmation, thank you.

2022-08-19 08:49 UTC, VenusGirl commented
Yes

2022-08-19 08:52 UTC, isaak654 approved these changes

2022-08-19 08:52 UTC, merged