Update sandman_zh_CN.ts
sandboxie-plus/Sandboxie pull request #2164
Opened 2022-08-20 14:44 UTC by Zerorigin

2022-08-20 17:56 UTC, isaak654 requested changes

2022-08-20 17:56 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_zh_CN.ts
> +        <translation>搜索选项</translation>
See <a href="https://user-images.githubusercontent.com/12372772/185760106-3f8a75c7-aefb-4cf8-a25f-02e6b65bc95d.png">Search for Options</a> for a visual comparison.

2022-08-20 17:56 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_zh_CN.ts
> +        <translation>搜索设置</translation>
See <a href="https://user-images.githubusercontent.com/12372772/185760093-6803d5d9-1e39-487a-ad1b-29fe32f8f9ed.png">Search for Settings</a> for a visual comparison.

2022-08-21 01:46 UTC, Zerorigin commented
The capitalization of English words does not affect the translation of Chinese.

2022-08-21 07:31 UTC, isaak654 approved these changes

2022-08-21 07:44 UTC, merged