Update SandMan.cpp
sandboxie-plus/Sandboxie pull request #2273
Opened 2022-09-25 07:02 UTC by okrc

Fixed the problem that `m_pCleanUpButton` UI is displayed empty when `NoIcons=1`.
<img width="632" alt="image" src="https://user-images.githubusercontent.com/29057533/192132161-185f3f38-da3d-4649-b33f-5beb7c418023.png">
<img width="617" alt="image" src="https://user-images.githubusercontent.com/29057533/192132194-0b135a19-8ab6-458d-9ba9-97d200378dc5.png">

2022-09-25 07:26 UTC, isaak654 requested changes
I think there should be a vertical separator between "Keep terminated" and "Cleanup".

2022-09-25 07:45 UTC, okrc commented
> I think there should be a vertical separator between "Keep terminated" and "Cleanup".

Added.

2022-09-25 07:53 UTC, isaak654 approved these changes

2022-09-25 08:11 UTC, isaak654 requested changes
I'm testing it with W7 x64, and there is no top border in the first two buttons:
![buttons_noicons](https://user-images.githubusercontent.com/12372772/192134283-8c441222-ed9c-4d50-bc85-c8732b649b28.png)

EDIT: it is a thing even in older Sandman builds.

2022-09-25 09:15 UTC, merged

2022-09-25 09:22 UTC, isaak654 commented
Of course, my last review still stands (merging or not).

2022-09-25 09:23 UTC, DavidXanatos commented
I have commented out the separator, its intended that the vertical bars are not ever ware, rest of the changes are in and active

2022-09-25 09:38 UTC, isaak654 commented
> I have commented out the separator, its intended that the vertical bars are not ever ware, rest of the changes are in and active

This might be fine, but the visual inconsistency with W7 (which is still supported in SBIE at this time) is still there.

2022-09-25 09:48 UTC, isaak654 commented
> I have commented out the separator, its intended that the vertical bars are not ever ware, rest of the changes are in and active

This might be fine, but the visual inconsistency with Win7 (which is still supported in SBIE at this time) is still there.

2022-09-25 09:59 UTC, okrc commented
@isaak654 I zoomed in several times and found that this problem also exists on Windows 11, which is supposed to be caused by m_pMenuBar.

2022-09-26 08:30 UTC, isaak654 commented
@okrc 
I can confirm that your latest modification works well in a separate test build.
If you're planning to create a new pull request with this modification, I'm going to merge it straight away.

2022-09-26 11:00 UTC, okrc commented
@isaak654
I created https://github.com/sandboxie-plus/Sandboxie/pull/2280