Fix: Autorun long path's over 130 characters (including NUL character) not currently supported
sandboxie-plus/Sandboxie pull request #2764
Opened 2023-03-25 17:51 UTC by Sapour

This is a simple patch to add support for auto-run paths up to 32767 WCHAR's (including NUL character).

It also fixes the bug where _countof() was used instead of sizeof(), since the RegQueryValueEx() expects the buffer size to be specified in bytes, not WCHAR's. Changing this on it's own would've increased max path length to 260 WCHAR's.

It's only for Sandboxie-Plus, but I plan on doing more comprehensive patch for everywhere MAX_PATH is currently used.

I have another patch which determine's required buffer size before-hand and only allocate's what's needed on the heap, but thought I'd keep it simple for starter's.

2023-03-25 18:46 UTC, DavidXanatos commented
could you please update the code to allocate the 32k buffer on the heap instead of the stack

2023-03-25 18:52 UTC, Sapour commented
Can I ask why you prefer it on the heap ?

Also, if you prefer it on the heap, you might as well use my other patch, which determine's the exact size of buffer required before-hand. I'll get it up-loaded and submit the other patch, and you can decide which to merge.

2023-03-25 18:55 UTC, isaak654 requested changes

2023-03-25 18:55 UTC, isaak654 commented on SandboxiePlus/SandMan/Helpers/WinAdmin.cpp
> +constexpr size_t MAX_PATH_EX = 32767; // Long file path max length, in character's
```suggestion
constexpr size_t MAX_PATH_EX = 32767; // Long file path max length, in characters
```

2023-03-26 07:29 UTC, DavidXanatos commented
Given that stack space is limited I find it a good practice to nut put things which are multiple pages large in the stack.
In this case its rather fine as we know the expected call depth to reach this function.
But for other sandboxie functions this might be problematic, so its best not to start with it, code tends to diffuse around with time (through reusing etc...)

2023-03-26 09:22 UTC, Sapour commented
Thanks for info, I'll get both this PR updated, and also submit the other patch I mentioned which doesn't need a fixed size buffer.

You can then pick which one you think is better.

2023-03-26 16:43 UTC, isaak654 approved these changes

2023-03-26 18:47 UTC, closed without merging