Typo fixes
sandboxie-plus/Sandboxie pull request #3070
Opened 2023-07-02 13:17 UTC by offhub

2023-07-02 13:49 UTC, isaak654 requested changes

2023-07-02 13:49 UTC, isaak654 commented on SandboxiePlus/SandMan/Troubleshooting/UI/desktop.js
> +let data1 = wizard.showForm(form1, tr('Select which  browser you want to create a shortcut for and in what box'));
```suggestion
let data1 = wizard.showForm(form1, tr('Select which browser you want to create a shortcut for and in what box'));
```

2023-07-02 13:49 UTC, isaak654 commented on SandboxiePlus/SandMan/Wizards/SetupWizard.cpp
> +    m_pHotfixes->setToolTip(tr("Check for latest compatibility tempaltes and hotfixes."));
```suggestion
    m_pHotfixes->setToolTip(tr("Check for latest compatibility templates and hotfixes."));
```

2023-07-02 14:04 UTC, isaak654 requested changes

2023-07-02 14:04 UTC, isaak654 commented on SandboxiePlus/SandMan/Wizards/BoxAssistant.cpp
> +    m_pAttachIni->setToolTip(tr("Sandboxing compatibility is reliant on the configuration hence attaching the sandboxie.ini helps a lot with finding the issue."));
```suggestion
    m_pAttachIni->setToolTip(tr("Sandboxing compatibility is reliant on the configuration hence attaching the Sandboxie.ini file helps a lot with finding the issue."));
```

2023-07-02 14:04 UTC, isaak654 commented on SandboxiePlus/SandMan/Troubleshooting/Sandboxing/installer.js
> +    { id: 'box', name: tr('Select a sandbox to instll into'), type: 'box' },
```suggestion
    { id: 'box', name: tr('Select a sandbox to install into'), type: 'box' },
```

2023-07-02 14:32 UTC, isaak654 requested changes
More fixes to be merged where applicable (from the private repo):
https://github.com/DavidXanatos/Sandboxie-Next/commit/e871ae7d92f04637e64733db6ffad981f12f4ded
https://github.com/DavidXanatos/Sandboxie-Next/commit/7389574785e46a570fb578c16a4ae07890bbffc2
https://github.com/DavidXanatos/Sandboxie-Next/commit/78267d98262513e4f8a6ad594fc0f4823f31ff9d
https://github.com/DavidXanatos/Sandboxie-Next/commit/632a6345ef7fc73a79a4c1fae50b27c314cc38db
https://github.com/DavidXanatos/Sandboxie-Next/commit/afeacb8c3b8ebad86e6b6bd802e4608c91d8ce6f
https://github.com/DavidXanatos/Sandboxie-Next/commit/35afd91590be7ad0cdd8730e32510626fd57f22c

2023-07-03 13:32 UTC, isaak654 commented
@DavidXanatos 
The following string updates to the `SettingsWindow.ui` file were suddenly reverted without notice: https://github.com/sandboxie-plus/Sandboxie/commit/fd73b2fa1fee6cdc58650b238eaefb586487a96e https://github.com/sandboxie-plus/Sandboxie/commit/1eccc1a9cf2b1f96adfd8d35b3ba0878f13f0e6f https://github.com/sandboxie-plus/Sandboxie/commit/c2a036ef4aef1bdd76dd4d0a057e8fdfebea5dbd

I'm aware of the issues you have with Qt Designer, so please make sure to apply manually the `SettingsWindow.ui` updates above or I'll have to abort this PR accordingly.

2023-07-03 13:58 UTC, DavidXanatos commented
changes re applied

2023-07-03 14:58 UTC, merged