Update Italian translation
sandboxie-plus/Sandboxie pull request #3087
Opened 2023-07-10 11:33 UTC by DerivativeOfLog7

As of creating, I did the .ts with a few entries still missing. I'll get them sorted out and check the other translation files as well

2023-07-10 17:40 UTC, isaak654 requested changes

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Sandboxie-Plus applica restrizioni ferree alle applicazione, che potrebbero causare problemi di compatibilità. Mantieni Sandboxie-Plus aggiornato, inclusi i modelli di compatibil
```suggestion
        <translation>Sandboxie Plus applica restrizioni ferree alle applicazioni, che potrebbero causare problemi di compatibilità. Mantieni Sandboxie Plus aggiornato, inclusi i modelli di compatibilità e risoluzione problemi, per garantire un corretto funzionamento in seguito ad aggiornamenti di Windows e delle applicazioni.</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>L&apos;accesso ai modelli di compatibilità più recenti e il database online di risoluzione problemi richiede un &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-cert&qu
```suggestion
        <translation>L&apos;accesso ai modelli di compatibilità più recenti e al database online di risoluzione problemi richiede un &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-cert&quot;&gt;certificato di supporto&lt;/a&gt; valido.</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Sandboxie-Plus Insider [%1]</translation>
```suggestion
        <translation>Sandboxie Plus Insider [%1]</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Impossibile inizializzare il COM</translation>
```suggestion
        <translation>Impossibile inizializzare il componente COM</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>&lt;br /&gt;&lt;font color=&apos;red&apos;&gt;Per la build corrente, le feature Plus rimangono abilitate&lt;/font&gt;, ma non si ha più accesso ai servizi di Sandboxie-Live, incl
```suggestion
        <translation>&lt;br /&gt;&lt;font color=&apos;red&apos;&gt;Per la build corrente, le funzioni Plus rimangono abilitate&lt;/font&gt;, ma non si ha più accesso ai servizi di Sandboxie Live, inclusi gli aggiornamenti di compatibilità e il database di risoluzione problemi.</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Benché questo certificato sia scaduto, le funzionalità Plus rimangono abilitate per la versione attualmente installata. Tuttavia, non si avrà più accesso ai servizi di Sandboxie-
```suggestion
        <translation>Benché questo certificato sia scaduto, le funzionalità Plus rimangono abilitate per la versione attualmente installata. Tuttavia, non si avrà più accesso ai servizi di Sandboxie Live, inclusi gli aggiornamenti di compatibilità e il database di risoluzione problemi.</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Ci scusiamo per il problema che si sta riscontrando con Sandboxie-Plus. </translation>
```suggestion
        <translation>Ci scusiamo per il problema che si sta riscontrando con Sandboxie Plus. </translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>This Insider build requires a special certificate of type GREAT_PATREON, PERSONAL-HUGE, or CONTRIBUTOR.</translation>
```suggestion
        <translation>Questa build insider richiede un certificato speciale GREAT_PATREON, PERSONAL-HUGE, o CONTRIBUTOR.</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Cerca nel canale Insider</translation>
```suggestion
        <translation>Cerca nel canale insider</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Il canale Insider offre accesso anticipato alle nuove funzionalità e risoluzioni di bug che saranno successivamente rilasciate al pubblico, in aggiunta a tutti i miglioramenti at
```suggestion
        <translation>Il canale insider offre accesso anticipato alle nuove funzionalità e risoluzioni di bug che saranno successivamente rilasciate al pubblico, in aggiunta a tutti i miglioramenti attinenti dal canale stabile.
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Info sul &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-insider&quot;&gt;canale Insider&lt;/a&gt;</translation>
```suggestion
        <translation>Info sul &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-insider&quot;&gt;canale insider&lt;/a&gt;</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Benvenuto nella procedura di risoluzione problemi guidata per Sandboxie-Plus. Questo assistente interattivo è progettato per aiutarti a risolvere problemi con l&apos;isolamento.<
```suggestion
        <translation>Benvenuto nella procedura di risoluzione problemi guidata per Sandboxie Plus. Questo assistente interattivo è progettato per aiutarti a risolvere problemi con l&apos;isolamento.</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>È in corso una procedura di risoluzione problemi, annullare la procedura guidata la interromperà, questo potrebbe lasciare l&apos;area virtuale in uno stato inconsistente.</trans
```suggestion
        <translation>È in corso una procedura di risoluzione problemi, annullare la procedura guidata la interromperà, questo potrebbe lasciare l&apos;area virtuale in uno stato incoerente.</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +Cliccare Fine per chuidere questa finestra.</translation>
```suggestion
Clicca su Fine per chiudere questa finestra.</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation type="unfinished">Impossibile inizializzare la procedura di risoluzione problemi. Cliccare su Successivo per inviare una segnalazione del problema.</translation>
```suggestion
        <translation type="unfinished">Impossibile inizializzare la procedura di risoluzione problemi. Clicca su Successivo per inviare una segnalazione del problema.</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation type="unfinished">Si è verificato un problema interno e la procedura di risoluzione problemi non può continuare. Cliccare successivo per inviare una segnalazione del problema.</t
```suggestion
        <translation type="unfinished">Si è verificato un problema interno e la procedura di risoluzione problemi non può continuare. Clicca su Successivo per inviare una segnalazione del problema.</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Configura updater di &lt;b&gt;Sandboxie-Plus&lt;/b&gt;</translation>
```suggestion
        <translation>Configura updater di &lt;b&gt;Sandboxie Plus&lt;/b&gt;</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Nel canale Insider - funzionalità esclusive</translation>
```suggestion
        <translation>Nel canale insider - funzionalità esclusive</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Il canale Insider offre accesso anticipato alle nuove funzionalità e risoluzioni di bug che saranno successivamente rilasciate al pubblico, in aggiunta a tutti i miglioramenti at
```suggestion
        <translation>Il canale insider offre accesso anticipato alle nuove funzionalità e risoluzioni di bug che saranno successivamente rilasciate al pubblico, in aggiunta a tutti i miglioramenti attinenti dal canale stabile.
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Info sul &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-insider&quot;&gt;canale Insider&lt;/a&gt;</translation>
```suggestion
        <translation>Info sul &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-insider&quot;&gt;canale insider&lt;/a&gt;</translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation></translation>
```suggestion
        <translation type="unfinished"></translation>
```

2023-07-10 17:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translatorcomment>hotfix non ha una traduzione?</translatorcomment>
```suggestion
        <translatorcomment>Chiedo conferma sulla possibilità di tradurre hotfix con correzione o correzione rapida.</translatorcomment>
```

2023-07-10 17:46 UTC, DerivativeOfLog7 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translatorcomment>hotfix non ha una traduzione?</translatorcomment>
Correzione rapida penso sia utilizzato rarissimamente

2023-07-10 17:47 UTC, DerivativeOfLog7 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Verificare regolarmente la presenza di aggiornamenti per Sandboxie-Plus e per i componenti facoltativi</translation>
È un problema delle stringhe sorgenti o è localizzato senza trattino?

2023-07-10 17:53 UTC, DerivativeOfLog7 commented
Dopo faccio uno squash

2023-07-10 18:11 UTC, isaak654 requested changes
According to [Report-Italian.txt](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/report/Report-Italian.txt), [Text-Italian-1040.txt](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/Text-Italian-1040.txt) needs also an update.

2023-07-10 18:11 UTC, DerivativeOfLog7 commented
> According to [Report-Italian.txt](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/report/Report-Italian.txt), [Text-Italian-1040.txt](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/Text-Italian-1040.txt) needs also an update.

Yes, I started with just the ts, I'll do the rest too

2023-07-10 18:23 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translatorcomment>hotfix non ha una traduzione?</translatorcomment>
So the choice would be between hotfix and correzione, I think.

2023-07-10 18:34 UTC, DerivativeOfLog7 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translatorcomment>hotfix non ha una traduzione?</translatorcomment>
Hotfix is used all the time, and "correzione" doesn't quite mean that, so I think it's just fine

2023-07-10 19:06 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translatorcomment>hotfix non ha una traduzione?</translatorcomment>
```suggestion

```

2023-07-11 13:19 UTC, isaak654 requested changes

2023-07-11 13:19 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation type="unfinished">Impossibile creare il cercatore di aggiornamenti</translation>
Better to look for other alternatives or not translating the sentence at all.

Some information sources:
https://github.com/sandboxie-plus/Sandboxie/blob/9407085cf60d8ac955b5f5d41f1e0c675a1c2165/SandboxiePlus/SandMan/SbiePlusAPI.cpp#L1125
https://learn.microsoft.com/en-us/windows/win32/api/wuapi/nf-wuapi-iupdatesearcher-search

2023-07-11 13:19 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation type="unfinished">Errore, istruzioni per la risoluzione dei problemi duplicate %1 (%2 &lt;-&gt; %3)!</translation>
```suggestion
        <translation type="unfinished">Errore, istruzioni duplicate per la risoluzione dei problemi %1 (%2 &lt;-&gt; %3)!</translation>
```

2023-07-11 13:19 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Le istruzioni per la risoluzione dei problemi scaricate sono corrotte!</translation>
```suggestion
        <translation>Le istruzioni scaricate per la risoluzione dei problemi sono corrotte!</translation>
```

2023-07-11 14:42 UTC, DerivativeOfLog7 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation type="unfinished">Impossibile creare il cercatore di aggiornamenti</translation>
Looking at the rest of the localization, it seems like it's better to translate it, but "ricercatore aggiornamenti" sounds weird to me... maybe I'm biased. If you can think of a better way to call it let me know

2023-07-11 21:40 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation type="unfinished">Impossibile creare il cercatore di aggiornamenti</translation>
It looks like I've only attached a partially related link, this is the right one: https://learn.microsoft.com/en-us/windows/win32/api/wuapi/nf-wuapi-iupdatesession-createupdatesearcher

Suggestions:

- "Impossibile creare l'interfaccia di ricerca degli aggiornamenti"
- "Impossibile creare l'interfaccia di ricerca"
- "Impossibile creare l'interfaccia IUpdateSearcher"
- "Impossibile creare l'interfaccia di ricerca IUpdateSearcher"

2023-07-11 21:41 UTC, DerivativeOfLog7 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation type="unfinished">Impossibile creare il cercatore di aggiornamenti</translation>
Yeah, "interfaccia di ricerca" sounds way more reasonable imo

2023-07-11 21:59 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translatorcomment>hotfix non ha una traduzione?</translatorcomment>
I doubt it's of any use now, unless you want to explain the definition to the Italian translators who will look at it.

2023-07-11 22:05 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translatorcomment>hotfix non ha una traduzione?</translatorcomment>
Fixed with c2349f5

2023-07-12 21:55 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation type="unfinished">Impossibile creare il cercatore di aggiornamenti</translation>
Fixed with a6cd359

2023-07-12 22:27 UTC, isaak654 requested changes
In some sentences I see the word  "guidata" better than in others.

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Risoluzione problemi guidata</translation>
```suggestion
        <translation>Risoluzione problemi</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Tutti i processi dell&apos;area virtuale devono essere interrotti prima che possa essere rinominata</translation>
```suggestion
        <translation>Tutti i processi dell&apos;area virtuale devono essere interrotti prima che possa essere rinominata.</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Impossibile muovere l&apos;immagine dell&apos;area virtuale &apos;%1&apos; in &apos;%2&apos;</translation>
```suggestion
        <translation>Impossibile spostare l&apos;immagine dell&apos;area virtuale &apos;%1&apos; in &apos;%2&apos;</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Se si desidera inviare una segnalazione del problema, controllare il riassunto sottostante e cliccare &quot;Fine&quot;.</translation>
```suggestion
        <translation>Se si desidera inviare una segnalazione del problema, controllare il riassunto sottostante e cliccare su &quot;Fine&quot;.</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +Se si è già un Great Supporter su Patreon, Sandboxie può verificare la presenza di un aggiornamento del tuo certificato online.</translation>
```suggestion
        <translation>Questa build insider richiede un certificato speciale del tipo GREAT_PATREON, PERSONAL_HUGE o CONTRIBUTOR.
Se si è già un Great Supporter su Patreon, Sandboxie può verificare la presenza di un aggiornamento del tuo certificato online.</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Questa è una &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-insider&quot;&gt;build insider esclusiva&lt;/a&gt; di Sandboxie Plus; è solo disponibile per i &lt;a href=
```suggestion
        <translation>Questa è una &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-insider&quot;&gt;build insider esclusiva&lt;/a&gt; di Sandboxie Plus solamente disponibile per i &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=patreon&quot;&gt;sostenitori Patreon&lt;/a&gt; dei livelli più alti, ai contributori del progetto, e ai possessori di un certificato di supporto HUGE.</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Sandboxie potrebbe generare i &lt;a href= &quot;sbie://docs/ sbiemessages&quot;&gt;Messaggi SBIE&lt;/a&gt; nel log dei messaggi e mostrarli come popup. Alcuni messaggi sono infor
```suggestion
        <translation>Sandboxie potrebbe generare i &lt;a href=&quot;sbie://docs/sbiemessages&quot;&gt;Messaggi SBIE&lt;/a&gt; nel log dei messaggi e mostrarli come popup. Alcuni messaggi sono informativi e notificano un evento comune, o in alcuni casi speciale, che si è verificato, mentre altri indicano una condizione di errore.&lt;br /&gt;Tramite l&apos;elenco in basso, è possibile indicare i messaggi SBIE da non mostrare come popup:</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Nascondi i processi di Sandboxie stesso dalla lista dei task</translation>
```suggestion
        <translation>Nascondi i processi di Sandboxie dalla lista dei task</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Mantieni gli script per la procedura di risoluzione problemi guidata aggiornati</translation>
```suggestion
        <translation>Mantieni gli script per la risoluzione problemi aggiornati</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Avvia procedura di risoluzione problemi guidata</translation>
```suggestion
        <translation>Avvia procedura di risoluzione problemi</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Ottieni gli script per la procedura di risoluzione problemi guidata più recenti</translation>
```suggestion
        <translation>Ottieni gli script più recenti per la procedura di risoluzione problemi</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Verifica la presenza di script per la procedura di risoluzione problemi guidata più recenti.</translation>
```suggestion
        <translation>Verifica la presenza di script più recenti per la procedura di risoluzione problemi.</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Benvenuto nella procedura di risoluzione problemi guidata per Sandboxie Plus. Questo assistente interattivo è progettato per aiutarti a risolvere problemi con l&apos;isolamento.<
```suggestion
        <translation>Benvenuto nella procedura guidata di risoluzione problemi per Sandboxie Plus. Questo assistente interattivo è progettato per aiutarti a risolvere problemi con l&apos;isolamento.</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Risoluzione problemi guidata</translation>
```suggestion
        <translation>Risoluzione guidata problemi</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Risoluzione problemi guidata</translation>
```suggestion
        <translation>Risoluzione guidata problemi</translation>
```

2023-07-12 22:27 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Grazie per aver utilizzato la procedura di risoluzione problemi guidata per Sandboxie Plus. Ci scusiamo per eventuali problemi riscontrati durante il processo. Se si hanno ulteri
```suggestion
        <translation>Grazie per aver utilizzato la procedura di risoluzione problemi per Sandboxie Plus. Ci scusiamo per eventuali problemi riscontrati durante il processo. Se si hanno ulteriori domande o si necessita di ulteriore assistenza, non esitare a contattarci. Siamo qui per aiutare. Grazie per la comprensione e la cooperazione.
```

2023-07-12 22:59 UTC, isaak654 requested changes

2023-07-12 22:59 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Oggetti barra degli strumenti</translation>
```suggestion
        <translation>Elementi barra degli strumenti</translation>
```

2023-07-13 07:57 UTC, DerivativeOfLog7 commented
Don't you love when an application made for TRANSLATING lacks a spell checking function

2023-08-08 20:54 UTC, isaak654 commented
I have just translated/added the missing entries and I think it is time to squash and merge this pull request.

2023-08-08 21:20 UTC, isaak654 requested changes

2023-08-08 21:20 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Per usare la funzione di stack trace sono richiesi DbgHelp.dll e SymSrv.dll, si desidera scaricarli e installarli?</translation>
```suggestion
        <translation>Per usare la funzione di traccia dello stack sono richiesti i file DbgHelp.dll e SymSrv.dll, si desidera scaricarli e installarli?</translation>
```

2023-08-08 21:20 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Salvataggio del trace log...</translation>
```suggestion
        <translation>Salvataggio del log di traccia...</translation>
```

2023-08-08 21:29 UTC, isaak654 requested changes

2023-08-08 21:29 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Con un &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-cert&quot;&gt;certificato di supporto&lt;/a&gt; valido, la procedura giudata sarebbe ancor più efficace, in quan
```suggestion
        <translation>Con un &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-cert&quot;&gt;certificato di supporto&lt;/a&gt; valido, la procedura guidata sarebbe ancor più efficace, in quanto avrebbe accesso al &lt;a href=&quot;https://sandboxie-plus.com/go.php?to=sbie-issue-db&quot;&gt;database online delle soluzioni&lt;/a&gt; per scaricare le ultime istruzioni per la risoluzione dei problemi.</translation>
```

2023-08-08 21:31 UTC, DerivativeOfLog7 commented
> I have just translated/added the missing entries and I think it is time to squash and merge this pull request.

can it be done at pull time?

2023-08-08 22:17 UTC, isaak654 requested changes

2023-08-08 22:17 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Verificare regolarmente la presenza di aggiornamenti per Sandboxie Plus e per i componenti facoltativi</translation>
```suggestion
        <translation>Verifica regolarmente la presenza di aggiornamenti per Sandboxie Plus e i componenti facoltativi</translation>
```

2023-08-08 22:17 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Selezionare da quale canale di aggiornamento verificare la presenza di nuove build di Sandboxie Plus:</translation>
```suggestion
        <translation>Seleziona da quale canale di aggiornamento verificare la presenza di nuove build di Sandboxie Plus:</translation>
```

2023-08-08 22:17 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Il canale insider offre accesso anticipato alle nuove funzionalità e risoluzioni di bug che saranno successivamente rilasciate al pubblico, in aggiunta a tutti i miglioramenti at
```suggestion
        <translation>Il canale insider offre accesso anticipato alle nuove funzionalità e risoluzioni di bug che saranno successivamente rilasciate al pubblico, in aggiunta a tutti i miglioramenti rilevanti dal canale stabile.
```

2023-08-08 22:17 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Mantieni la lista del componenti aggiuntivi facoltativi aggiornata</translation>
```suggestion
        <translation>Mantieni la lista dei componenti aggiuntivi facoltativi aggiornata</translation>
```

2023-08-08 22:42 UTC, isaak654 requested changes

2023-08-08 22:42 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +Clicca su Fine per chiudere questa finestra.</translation>
```suggestion
Clicca su Fine per concludere la procedura guidata.</translation>
```

2023-08-08 23:03 UTC, isaak654 requested changes

2023-08-08 23:07 UTC, isaak654 requested changes

2023-08-08 23:07 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Mantieni modelli di compatibilità aggiornati e applica hotfix</translation>
```suggestion
        <translation>Mantieni aggiornati i modelli di compatibilità e applica hotfix</translation>
```

2023-08-08 23:09 UTC, isaak654 requested changes

2023-08-08 23:09 UTC, isaak654 commented on SandboxiePlus/SandMan/sandman_it.ts
> +        <translation>Sandboxie Plus applica restrizioni ferree alle applicazioni, che potrebbero causare problemi di compatibilità. Mantieni Sandboxie Plus aggiornato, inclusi i modelli di compatibil
```suggestion
        <translation>Sandboxie Plus applica restrizioni ferree alle applicazioni, che potrebbero causare problemi di compatibilità. Mantieni aggiornato Sandboxie Plus, inclusi i modelli di compatibilità e risoluzione problemi, per garantire un corretto funzionamento in seguito ad aggiornamenti di Windows e delle applicazioni.</translation>
```

2023-08-09 08:44 UTC, DerivativeOfLog7 commented
> I have just translated/added the missing entries and I think it is time to squash and merge this pull request.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review

2023-08-09 11:33 UTC, isaak654 approved these changes

2023-08-09 11:35 UTC, merged