Adds missing translation files for troubleshooting scripts
sandboxie-plus/Sandboxie pull request #3417
Opened 2023-10-30 19:47 UTC by offhub

Except for Turkish/Deutsche, all others are in English.

2023-10-31 16:41 UTC, isaak654 requested changes
This pull request contains the following display issue, which I can reproduce: https://github.com/sandboxie-plus/Sandboxie/issues/3293#issuecomment-1785947050

2023-10-31 19:43 UTC, isaak654 approved these changes

2023-10-31 19:58 UTC, isaak654 reviewed
My only remaining doubt is related to the way these files will be updated, any clarification is appreciated.

2023-11-19 09:21 UTC, DavidXanatos commented
I would add it and just see what if it works out in weblate

2023-11-19 09:22 UTC, merged