An update of Text-SimpChinese-2052.txt
sandboxie-plus/Sandboxie pull request #3579
Opened 2024-01-25 14:39 UTC by RimacC2-EV

This update changes some translation terms that may be awkward to read. (I haven't used Sandboxie before, may modify some translations that shouldn't have been changed)

Thank you for your contribution to the Sandboxie repository.

In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request" option. 

In addition, you can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

All new translators are encouraged to look at the "Localization notes and tips" before creating a pull request: https://git.io/J9G19

2024-01-25 14:46 UTC, RimacC2-EV commented
Since I haven't used Sandboxie Classic before, I've made fewer changes to the translation this time to avoid changing the translation file to an incomprehensible or wrong one.

2024-01-25 23:25 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
If the intention was to replace "programs" with "windows", then I prefer the original.

2024-01-25 23:25 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1313 已阻止进程 '%2' 对磁盘进行直接访问
I have tried various online translators to understand the meaning, but the results diverge.
See my suggestion in https://github.com/sandboxie-plus/Sandboxie/pull/3575#issuecomment-1910721131

2024-01-25 23:27 UTC, isaak654 requested changes

2024-01-25 23:27 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
If the intention was to replace "programs" with "windows", then I prefer the original.

2024-01-25 23:41 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
If you intended to replace "programs" with "windows", then I prefer the original.

2024-01-25 23:42 UTC, isaak654 requested changes

2024-01-25 23:42 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
If you intended to replace "programs" with "windows", then I prefer the original.

2024-01-25 23:51 UTC, isaak654 requested changes

2024-01-25 23:51 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
If you intended to replace "programs" with "windows", then I prefer the original entry.

2024-01-25 23:54 UTC, isaak654 requested changes

2024-01-25 23:54 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
If you intended to replace "programs" with "windows", then I prefer the original entry.

2024-01-25 23:58 UTC, isaak654 requested changes

2024-01-25 23:58 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
If you intended to replace "programs" with "windows", then I prefer the original sentence.

2024-01-26 00:00 UTC, isaak654 requested changes

2024-01-26 00:00 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
If you intended to replace "programs" with "windows", then I would recommend the original sentence.

2024-01-26 00:05 UTC, isaak654 requested changes

2024-01-26 00:05 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
I would recommend to restore the original sentence.

2024-01-26 03:03 UTC, nkh0472 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1313 已阻止进程 '%2' 对磁盘进行直接访问
Maintaining the current strings in SBie Classic is recommended. Consider altering them only after a comprehensive review of all related items. For reference, check examples like L2822-2831, L2900-2909, and so on.

2024-01-26 03:17 UTC, nkh0472 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
Initialization failure may be due to other programs. The original string is better.

2024-01-27 09:31 UTC, RimacC2-EV commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
Okay, I'll rewrite these strings in the next changes, thanks for the support!

2024-01-27 14:41 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
I still think the original sentence is better in this case.

2024-01-27 14:46 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
I still think the original sentence is better in this case. 

Perhaps an expression like "all programs in use" could be used.

2024-01-27 14:48 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
I still think the original sentence is better in this case. 

Perhaps an expression like "Close all programs in use" could be used, without parentheses.

2024-01-27 14:49 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
I still think the original sentence is better in this case. 

Perhaps an expression such as "Close all programs in use" could be added, without parentheses.

2024-02-01 21:44 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
With the premise that I would prefer a review by someone who knows Simplified Chinese better than I do.

2024-02-01 21:56 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
With the premise that I would prefer a review by someone who knows Simplified Chinese or otherwise close this pull request.

2024-02-01 21:58 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
With the premise that I would prefer a final review by someone who knows Simplified Chinese or otherwise this pull request can be closed.

2024-02-01 22:01 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
> Perhaps an expression such as "Close all programs in use" could be interesting, without parentheses.

With the premise that I would prefer a final review by someone who knows Simplified Chinese or otherwise this pull request can be closed.

2024-02-01 22:04 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
> Perhaps an expression such as "Close all programs in use" could be interesting, without parentheses.

With the premise that I would like a final review by someone who knows Simplified Chinese or otherwise this pull request can be closed.

2024-02-01 22:29 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
>> Perhaps an expression such as "Close all programs in use" could be interesting, without parentheses.
>
> <img alt="review request from RimacC2-EV" src="https://github.com/sandboxie-plus/Sandboxie/assets/12372772/7550e5ff-5f2d-495b-951a-aa1fc635f577" height="27px"> 

With the premise that I would like a final review by someone who knows Simplified Chinese or otherwise this pull request can be closed... also because it seems that my suggestion was not considered at all, at least according to DeepL Translate and Bing Chat.

2024-02-01 22:30 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
>> Perhaps an expression such as "Close all programs in use" could be interesting, without parentheses.
>
> <img alt="review request from RimacC2-EV" src="https://github.com/sandboxie-plus/Sandboxie/assets/12372772/7550e5ff-5f2d-495b-951a-aa1fc635f577" height="27px"> 

With the premise that I would like a final review by someone who knows Simplified Chinese or otherwise this pull request can be closed... it seems that my suggestion was not considered at all, at least according to DeepL Translate and Bing Chat.

2024-02-01 22:31 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
>> Perhaps an expression such as "Close all programs in use" could be interesting, without parentheses.
>
> <img alt="review request from RimacC2-EV" src="https://github.com/sandboxie-plus/Sandboxie/assets/12372772/7550e5ff-5f2d-495b-951a-aa1fc635f577" height="27px"> 

With the premise that I would like a final review by someone who knows Simplified Chinese or otherwise this pull request can be closed... it seems that my suggestion was not considered at all, at least according to DeepL Translator and Bing Chat.

2024-02-01 22:39 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1313 已阻止进程 '%2' 对磁盘进行直接访问
In this case I fully agree, please restore the original sentence.

2024-02-01 22:47 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
>> Perhaps an expression such as "Close all programs in use" could be interesting, without parentheses.
>
> <img alt="review request from RimacC2-EV" src="https://github.com/sandboxie-plus/Sandboxie/assets/12372772/7550e5ff-5f2d-495b-951a-aa1fc635f577" height="27px"> 

It seems that my suggestion was not considered, at least according to the results provided by DeepL Translator and Bing Chat, so why should I consider this pull request?

2024-02-01 23:25 UTC, isaak654 commented on Sandboxie/msgs/Text-SimpChinese-2052.txt
> +SBIE1153 Sandboxie 初始化失败。请关闭所有 Sandboxie 窗口后重新安装 Sandboxie，或者重新启动您的计算机。
>> Perhaps an expression such as "Close all programs in use" could be interesting, without parentheses.
>
> <img alt="review request from RimacC2-EV" src="https://github.com/sandboxie-plus/Sandboxie/assets/12372772/7550e5ff-5f2d-495b-951a-aa1fc635f577" height="27px"> 

It seems that my suggestion was not properly considered, at least according to the results provided by DeepL Translator and Bing Chat, so why should I consider this pull request? I'm against the current changes, so maybe it would be better to close it here.

2024-02-01 23:27 UTC, isaak654 requested changes
>Perhaps an expression such as "Close all programs in use" could be interesting, without parentheses.

It seems that my suggestion was not properly considered, at least according to the results provided by DeepL Translator and Bing Chat. I'm against the current changes, so maybe it would be better to close the pull request.

2024-02-01 23:39 UTC, isaak654 requested changes
https://github.com/sandboxie-plus/Sandboxie/pull/3579#discussion_r1467181690

2024-02-01 23:46 UTC, isaak654 requested changes
https://github.com/sandboxie-plus/Sandboxie/pull/3579#discussion_r1468497127

It appears that none of these suggestions were adequately considered. I'm against the current changes, so maybe it would be better to close the pull request.

2024-02-02 00:22 UTC, RimacC2-EV commented
I'm sorry I didn't make valid changes, thanks for the suggestions, I'll resend the pull request afterward.

2024-02-02 00:22 UTC, RimacC2-EV commented
I'm sorry I didn't make valid changes, thanks for the suggestions, I'll resend the pull request afterward.

2024-02-02 00:22 UTC, closed without merging