Update sandman_zh_TW.ts
sandboxie-plus/Sandboxie pull request #4191
Opened 2024-08-28 13:41 UTC by ydx1013

> Thank you for your contribution to the Sandboxie repository.
>
> In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request" option.
>
> In addition, you can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".
>
> All new translators are encouraged to look at the "Localization notes and tips" before creating a pull request: https://git.io/J9G19

2024-08-28 16:54 UTC, DavidXanatos commented
please fix: 
lrelease error: Parse error at ..\SandMan\sandman_zh_TW.ts:9008:21: Expected '>' or '/', but got '"'.

2024-08-28 17:02 UTC, DavidXanatos requested changes

2024-08-28 17:02 UTC, DavidXanatos commented on SandboxiePlus/SandMan/sandman_zh_TW.ts
> +        <translation">進程隱藏</translation>
here remove the " bevore the >

2024-08-29 00:28 UTC, ydx1013 reviewed
Finish review

2024-08-29 09:35 UTC, merged