CleanAfterReboot
sandboxie-plus/Sandboxie pull request #4222
Opened 2024-09-08 07:26 UTC by Jkkoi

The PR provides a menu action to clean FileRootPath of a box after the machine reboot.

2024-09-08 07:48 UTC, DavidXanatos commented
The code does not compile, see failed CI runs.
Further more, I'm not sure if a feature like this implemented this way is desirable. 
Not all sandboxes may be intended to be deleted, some may contain persistent software installations, etc.
This feature also bypasses the snapshot mechanism and just deletes all.
Imho it should be implemented differently allow per box granularity and the ability to roll back to last snapshot instead of deleting all.

2024-09-08 08:49 UTC, love-code-yeyixiao commented on SandboxiePlus/SandMan/Views/SbieView.cpp
> +			if(MoveFileExW(fileRoot.toStdString().c_str(),NULL,4)==0){
ExW->ExA

2024-09-08 12:09 UTC, DavidXanatos commented
```if(MoveFileExW(fileRoot.toStdWString().c_str(),NULL,4)==0){```
would be better as it would work with unicode paths, 
but that does not address my initial concerns, imho such a feature should be implemented in sandman in a way that basically triggers the normal delete box content code path for selected boxes after reboot.
and not using windows delayed file operations

2024-09-08 12:25 UTC, Jkkoi commented
This will ensure that the deletion operation gets done reliably, especially if Sandman doesn't boot itself at boot time.

2024-09-16 11:36 UTC, Jkkoi commented
@DavidXanatos   Please review it.❤️

2024-09-17 02:31 UTC, love-code-yeyixiao commented on SandboxiePlus/SandMan/Views/SbieView.cpp
> +                if(MoveFileExW(fileRoot.toStdString().c_str(),NULL,4)==0){
MoveFileExW->MoveFileExA

2024-09-17 03:37 UTC, Jkkoi commented
@DavidXanatos I have provided another clean option.

2024-09-17 11:54 UTC, offhub commented
It might be better to check for a 'DON'T-USE.TXT' file in both the sandbox directory and its parent directory. If the files are not found, the operation (MoveFileEx) should be aborted.


![sbiePR4222-dontuse](https://github.com/user-attachments/assets/de882b95-d987-4096-81e1-9ebfae4120a8)

2024-09-17 12:19 UTC, offhub requested changes

2024-09-17 12:19 UTC, offhub commented on SandboxiePlus/SandMan/Views/SbieView.cpp
> +		tr("Do you want to make the box cleaned after machine reboot?"),
```suggestion
		tr("Do you want the box to be cleaned after the machine reboots?"), 
```

2024-09-17 12:19 UTC, offhub commented on SandboxiePlus/SandMan/Views/SbieView.cpp
> +            tr("Do you want to use Windows Delecting Feature(MoveFileEx)?Or we'll delete the box when Sandman.exe called by userinit.exe."),
```suggestion
            tr("Do you want to use the Windows deleting function (MoveFileEx), or delete the box when SandMan.exe starts?"),
```

2024-09-17 12:19 UTC, offhub commented on SandboxiePlus/SandMan/Views/SbieView.cpp
> +                    tr("The operation failed,please make sure that Sandman has admin privliage.")
```suggestion
                    tr("The operation failed. Please make sure that SandMan has administrative privileges.")
```

2024-11-13 11:22 UTC, DavidXanatos commented
Did you test the behavior if MoveFileEx when the to be deleted sandbox contains symlinkd and or directory junctions.
Also with the new file permission scheme used in 1.15.x we in particular 'UseOriginalACLs=y' MoveFileEx may not have enough permissions to delete the folder.

Hence executive decision:
We will not use MoveFileEx to delete files on reboot, at all.

In an upcoming build of Sandboxie we well add a mechanism to perform the deletion by sbiesvc with system privileges, for that we need to ensure that we don't open a backdoor allowing anyone to delete any folder on the system willy-nilly, checking for the presence of DON'T-USE.TXT or a sbie desktop.ini is a good start, although I think ultimately we will use the ACLs of the containing folder that is if the user has permissions to delete the parent folder we grant these permissions to all sub folders even if inheritance is disabled and that permission is not set for a sub folder or file.

If we desire to implement a delete after reboot feature we can tie this into that new service functionality.
Therefor I'll close this pull request now.

@Jkkoi You are very welcome to help with the new service based approach.

2024-11-13 11:22 UTC, closed without merging