Add VLC Media Player to the templates
sandboxie-plus/Sandboxie pull request #708
Opened 2021-03-25 11:29 UTC by Dyras

Hello! I've added VLC Media Player to the templates. I've created the new "MediaPlayer" class for it, and I'm planning on expanding that class with MPC-HC if you're OK with this pull request :)

I've also added an option for VLC to access the AppData in order to save the settings, and another one for access to the pictures folder to save screenshots.

Tested by me, and it works great.

2021-03-25 12:09 UTC, isaak654 commented
> 
> 
> I've created the new "MediaPlayer" class for it, and I'm planning on expanding that class with MPC-HC if you're OK with this pull request :)
> 

Good idea, but it's not enough to add a new class in the templates.ini. For example, I can't see those VLC templates represented in the UI of Sbie Classic.

I never did it before, but after browsing the source code, I think you need to apply the class in these files too:
https://github.com/sandboxie-plus/Sandboxie/search?q=EmailReader

2021-03-25 12:21 UTC, isaak654 requested changes
It's not enough to add a new class in templates.ini. Only with these edits, VLC templates won't be represented in the UI of Sbie Classic.

After browsing the source code, I think you need to apply the new class in these files too: 
https://github.com/sandboxie-plus/Sandboxie/search?q=EmailReader
https://github.com/search?q=org%3Asandboxie-plus+4391&type=code
https://github.com/search?q=org%3Asandboxie-plus+4392&type=code

Note: about the latest two links, it's enough to update Sbie-English-1033.txt. I showed them to you in order to understand the connections.

2021-03-25 13:12 UTC, Dyras commented
I think I've added it everywhere now, aside from in the Sbie-English-1033.txt. Am I to assume I should use the number that comes after the last used one?

2021-03-25 13:24 UTC, isaak654 requested changes

2021-03-25 13:24 UTC, isaak654 commented on Sandboxie/apps/control/AppPage.cpp
> +    m_app_pages.AddTail(new CAppPage(&info, BoxName));
1) The two IDs are the same of EmailReader, so it would be better to create new IDs in Sbie-English-1033.txt. They contain a title and a detailed description displayed in Sbie Classic.
2) Considering that this class will be displayed in Sbie Classic, it will be rendered in a certain order. Please move the entire MediaPlayer block under Desktop class:
![immagine](https://user-images.githubusercontent.com/12372772/112479448-5748a200-8d75-11eb-93c1-e34eb640ea9d.png)

2021-03-25 13:35 UTC, Dyras commented
Aye aye sir, everything seems to be ready now!

2021-03-25 13:55 UTC, isaak654 requested changes
> Aye aye sir, everything seems to be ready now!

In theory, yes. I never reviewed a new category before.

One last change:

2021-03-25 13:55 UTC, isaak654 commented on Sandboxie/msgs/Sbie-English-1033.txt
> +Force VLC Media Player to run in the Sandbox
Change it to:
Force VLC Media Player to run in this sandbox

2021-03-25 14:09 UTC, isaak654 requested changes

2021-03-25 14:09 UTC, isaak654 commented on Sandboxie/msgs/Sbie-English-1033.txt
> +4397;txt;01
You need to start a new line before this string.

2021-03-25 14:11 UTC, isaak654 commented on Sandboxie/msgs/Sbie-English-1033.txt
> +
Remove the additional space here.

2021-03-25 14:34 UTC, isaak654 requested changes

2021-03-25 14:34 UTC, isaak654 commented on Sandboxie/install/Templates.ini
> +
I don't know if the placement would affect Sbie Classic order, but I would move it before the Download Managers block (just in case).

2021-03-25 14:34 UTC, Dyras commented
@DavidXanatos I got a template ready for SumatraPDF. Do you want that under Misc, Print or something else?

Print only seems to have actual printing, Misc seems to have nothing but compatibility. Or do you perhaps want a PDF class too?

2021-03-25 14:42 UTC, isaak654 commented
> 
> 
> @DavidXanatos I got a template ready for SumatraPDF. Do you want that under Misc, Print or something else?
> 
> Print only seems to have actual printing, Misc seems to have nothing but compatibility. Or do you perhaps want a PDF class too?

In Classic, the Print section is displayed as PDF/Printing (as in the attachment below). Probably it would be more simple to rename the one in Plus (in my opinion).

![image](https://user-images.githubusercontent.com/12372772/112479448-5748a200-8d75-11eb-93c1-e34eb640ea9d.png)

2021-03-25 15:36 UTC, isaak654 commented on Sandboxie/apps/control/AppPage.cpp
> +    info.LabelId = MSG_4394;
Considering your latest changes, you can even replace MSG_4394 with the existent MSG_4207:
https://github.com/sandboxie-plus/Sandboxie/blob/d34ba4d9a6784629b1c5e3779d3a5848702555cb/Sandboxie/msgs/Sbie-English-1033.txt#L2909-L2910

and remove 4394;txt;01 from Sbie-English-1033.txt.

It's your call, it depends on which string you like more.

2021-03-25 16:39 UTC, isaak654 requested changes

2021-03-25 16:39 UTC, isaak654 commented on Sandboxie/msgs/Sbie-English-1033.txt
> +Allow VLC direct access to the Photo folder for easier screenshotting.
I would replace 'for easier screenshotting' with 'for easier screen capture'.

2021-03-25 16:59 UTC, Dyras commented on Sandboxie/apps/control/AppPage.cpp
> +    info.LabelId = MSG_4394;
Yeah I think you're right. The other message isn't awfully specific, IMO.

2021-03-27 11:50 UTC, Dyras commented
I've added everything from this into https://github.com/sandboxie-plus/Sandboxie/pull/719 so go look at that one instead :)

2021-03-27 11:50 UTC, closed without merging