Prevent VLC from importing media files
sandboxie-plus/Sandboxie pull request #743
Opened 2021-04-01 10:30 UTC by Dyras

Hello! This prevents VLC from importing media files if the template is used.

Until a better fix is available, this fixes https://github.com/sandboxie-plus/Sandboxie/issues/536

2021-04-01 11:00 UTC, Dyras commented
Any thoughts on this approach is appreciated @DavidXanatos

2021-04-09 08:49 UTC, DavidXanatos commented
Eider add these for all the known players, or a global tamplate that prevents copying of media files would be better

2021-04-13 11:49 UTC, Dyras commented
@DavidXanatos I've added a template for this now. Going to add mp3 and the like later.

2021-04-14 20:16 UTC, isaak654 requested changes

2021-04-14 20:16 UTC, isaak654 commented on Sandboxie/install/Templates.ini
> +
Consider adding .wav, .wma, .ape audio extensions.

2021-04-19 02:38 UTC, isaak654 requested changes

2021-04-19 02:38 UTC, isaak654 commented on Sandboxie/install/Templates.ini
> +
Consider to add .mpg, .mpeg, .mov, .webm, .f4v, .rm, .swf, .ts or other video formats listed here: 
https://filesamples.com/categories/video
You can do the same with audio formats like .ac3, .oga, .aiff, .ra, .cdda, or others: 
https://filesamples.com/categories/audio

2021-04-19 18:28 UTC, Dyras commented
Unless there is something else that I've missed, I think that's all.

2021-06-02 16:50 UTC, merged

2022-12-30 21:39 UTC, isaak654 commented
Note: `DontCopy=*.ts` was recently commented out from Templates.ini in commit https://github.com/sandboxie-plus/Sandboxie/commit/a21d41af17a46a66c721b602515fee6d00006b58 because it breaks Cyberpunk 2077 compatibility. However, you can still add it in your Sandboxie.ini configuration to make it permanent.