Update Changelog 5.49.7
sandboxie-plus/Sandboxie pull request #775
Opened 2021-04-11 17:28 UTC by NewKidOnTheBlock

Thank you for your contribution to the Sandboxie repository.

In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request". You can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

2021-04-15 03:07 UTC, isaak654 approved these changes

2021-04-15 03:36 UTC, isaak654 requested changes
Mmm, maybe you just need to improve this:

2021-04-15 03:36 UTC, isaak654 commented on CHANGELOG.md
> +- fixed sandbox links receiving double extension
- fixed the creation of new sandbox links receiving double extension

It's related to #770

2021-04-15 15:10 UTC, NewKidOnTheBlock commented on CHANGELOG.md
> +- fixed sandbox links receiving double extension
Hmm. I don't know how to edit a pull request short of deleting the whole thing and creating a new one.

2021-04-15 16:12 UTC, isaak654 requested changes

2021-04-15 16:12 UTC, isaak654 commented on CHANGELOG.md
>  --- "OpenUPnP=y", "OpenBluetooth=y", "OpenSmartCard=n" use the new templates instead
Suggestion:
--- "OpenUPnP=y", "OpenBluetooth=y", "OpenSmartCard=n", so use the new RPC templates instead

2021-04-16 07:03 UTC, NewKidOnTheBlock commented on CHANGELOG.md
>  --- "OpenUPnP=y", "OpenBluetooth=y", "OpenSmartCard=n" use the new templates instead
This completely changes the meaning (not to claim that I have understood line 54):

Before
"(This), (this) and (this) all use the new template."

After
"(This), (this) and (this) have been removed, so you should use the new template."

2021-04-16 13:35 UTC, isaak654 commented on CHANGELOG.md
>  --- "OpenUPnP=y", "OpenBluetooth=y", "OpenSmartCard=n" use the new templates instead
I think the second is more appropriate, for example there is a lot of disabled code with double slashes if you search OpenBluetooth in the source: https://github.com/sandboxie-plus/Sandboxie/search?q=OpenBluetooth

Besides, the new templates write different values:
```
Template=SSDP
Template=OpenSmartCard
Template=OpenBluetooth
```

2021-04-16 13:50 UTC, isaak654 approved these changes
I think you can remove the draft status from the pull request.

2021-06-02 16:50 UTC, merged