Update sandman_zh-CN.ts
sandboxie-plus/Sandboxie pull request #888
Opened 2021-06-11 02:29 UTC by TianXing-Yi

Thank you for your contribution to the Sandboxie repository.

In order to reduce the risk of accidental merges, it's highly recommended for beginners to open a new Pull Request in draft state by clicking the button "Create Draft Pull Request", instead of using the default "Create Pull Request". You can convert an existing pull request to a draft by clicking the "Convert to draft" link in the right sidebar under "Reviewers".

2021-06-14 20:54 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>无法复制 RegHive</translation>
听上去是拒绝完成、不可执行而非失败。

2021-06-14 20:54 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>无法连接服务器</translation>
刻意与connecting有所区分

2021-06-14 20:55 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>关于 %1，如果您希望在沙盒浏览器中打开，请选“是”，反之“否”。</translation>
沙盒浏览器 听上去像单独的软件/窗口。

2021-06-14 20:57 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>拖拽探查工具到窗口上，即可检查此程序是否来自沙盒。</translation>
个人倾向讲细一些，"窗口上"和"此程序"可能理解为工具本身。

2021-06-14 20:57 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>打开浏览器</translation>
有误解为文件浏览器的可能。

2021-06-14 21:00 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>沙盒不能以设备命名。</translation>
设备名称我想是术语（保留名称）。而设备的名称过于宽泛。

2021-06-14 21:00 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>无法删除沙盒 %1: %2</translation>
无法（cannot）可能指禁止（拒绝/保护），也可能指失败。

2021-06-14 21:02 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>无法停止全部的 Sandboxie 组件</translation>
这个我觉得可以。

2021-06-14 21:04 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>允许 %1 (%2) 访问网络吗？
加上“要”是否更体现这是添加规则而非仅本次操作？

2021-06-14 21:05 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>允许 %1 (%2) 使用打印服务在沙盒外写入吗？</translation>
沙盒外是“副作用”，而“使用”似乎是目的。

2021-06-14 21:08 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>RT 必须指定接口名称。</translation>
这样翻译感觉怪怪的，有什么理由吗。

2021-06-14 21:09 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>COM 必须指定对象 GUID，例如：{00000000-0000-0000-0000-000000000000}</translation>
"COM"什么未表明（只能理解为“COM 设置必须用……”，修改的目的是？

2021-06-14 21:10 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>请输入程序路径</translation>
对所有的"一个"，因为原文有指明而非the，我倾向指明。

2021-06-14 23:18 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>无法复制 RegHive</translation>
嗯 复制失败更合理

2021-06-14 23:24 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>无法连接服务器</translation>
只是觉得怪怪的，生活中很少见到“联通服务器”

2021-06-14 23:33 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>关于 %1，如果您希望在沙盒浏览器中打开，请选“是”，反之“否”。</translation>
“如果您希望在沙盒化的浏览器中打开”，这个

2021-06-14 23:35 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>拖拽探查工具到窗口上，即可检查此程序是否来自沙盒。</translation>
”拖拽探查工具到窗口上，即可检查此程序是否沙盒化“

2021-06-14 23:39 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>打开浏览器</translation>
正常使用，会以“文件夹”、“浏览器”，区分这两者。

2021-06-14 23:43 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>沙盒不能以设备命名。</translation>
一句话里，出现两个相同的词语，不觉得很绕口吗？  “请问您早上吃的啥早餐？” 和 “请问您早餐吃了啥？”

2021-06-14 23:44 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>无法删除沙盒 %1: %2</translation>
这个赞成原文

2021-06-15 00:00 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>允许 %1 (%2) 访问网络吗？
没这个必要，只会觉得多，

2021-06-15 00:30 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>允许 %1 (%2) 使用打印服务在沙盒外写入吗？</translation>
这个没感觉出区别，语言简洁些了，功能用户一试便知

2021-06-15 00:33 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>RT 必须指定接口名称。</translation>
感觉两个都不太好，不够直白

2021-06-15 00:35 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>COM 必须指定对象 GUID，例如：{00000000-0000-0000-0000-000000000000}</translation>
汉语语法动词前置，这样翻译更好：”COM 对象必须指定其 GUID“

2021-06-15 00:36 UTC, TianXing-Yi commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>请输入程序路径</translation>
没这个必要，原文是引导用户输入路径，默认情况用户也只会输入一个； 若需要多个路径，翻译也就不是这样了

2021-06-15 04:56 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>无法连接服务器</translation>
如果这个reachable仅是TCP连接，那么确实连接就行。如果HTTP错误（404、503等）也算进去了，连通（通信）更好。

2021-06-15 04:56 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>关于 %1，如果您希望在沙盒浏览器中打开，请选“是”，反之“否”。</translation>
可。

2021-06-15 04:57 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>拖拽探查工具到窗口上，即可检查此程序是否来自沙盒。</translation>
”拖拽探查工具到窗口上，即可检查其程序是否被沙盒化。“

2021-06-15 04:58 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>打开浏览器</translation>
"浏览器"还是挺广泛的，比如图片浏览器等。虽然日常指上网那个，但此处指明没坏处。

2021-06-15 05:00 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>沙盒不能以设备命名。</translation>
或许翻译腔，但如果设备名称指保留名称，似乎这样更准确，原文也两次name。"以设备命名"可能很宽泛的理解，“PC” "手机" PC机器名称等。

2021-06-15 05:02 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>允许 %1 (%2) 使用打印服务在沙盒外写入吗？</translation>
只是倾向"利用"，因为程序的正常目的是打印而非进行越界写入。使用，也行吧。

2021-06-15 05:05 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>请输入程序路径</translation>
如果描述没说、界面支持，我会试试能否一次多个。看上去界面是单行输入框，那么简洁也行。

2021-06-16 08:43 UTC, yuhao2348732 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>无法连接服务器</translation>
本身英文原文缺少系动词，服务器无法连通（连接）都可以

2021-06-16 08:45 UTC, yuhao2348732 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>拖拽探查工具到窗口上，即可检查此程序是否来自沙盒。</translation>
”拖拽探查工具到窗口上，即可检查其程序是否被沙盒化。“     +1

2021-06-16 08:47 UTC, yuhao2348732 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>沙盒不能以设备命名。</translation>
不想当将军的士兵不是好士兵

2021-06-16 08:51 UTC, yuhao2348732 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>RT 必须指定接口名称。</translation>
RT interfaces是一个词组，RT接口必须指定名称   这样或许好一点

2021-06-17 00:15 UTC, yfdyh000 commented on SandboxiePlus/SandMan/sandman_zh-CN.ts
> +        <translation>RT 必须指定接口名称。</translation>
"RT接口必须指定名称" 听上去很大歧义，理解为"给RT接口指定一个名称"，而实际是"给RT接口指定一个RT接口名称"。

2021-09-12 14:09 UTC, isaak654 requested changes
This pull request has 14 conflicts that must be resolved if you want to keep it alive.

2021-09-22 17:52 UTC, closed without merging